name: loopus
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  cached_network_image: ^3.1.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.1
  image_picker: ^0.8.4+4
  smooth_page_indicator: ^1.0.0+2
  http: ^0.13.4
  image_cropper: ^1.4.1
  device_preview: ^1.0.0
  pull_to_refresh: ^2.0.0
  sticky_headers: ^0.2.0
  underline_indicator: ^0.0.4
  webview_flutter: ^3.0.0
  firebase_messaging: ^13.0.0
  firebase_core: ^1.21.1
  firebase_analytics: ^9.3.3
  intl: ^0.17.0
  lottie: ^1.2.1
  flutter_datetime_picker: ^1.5.0
  # kakao_flutter_sdk: ^0.9.0
  flutter_keyboard_visibility: ^5.1.1
  dropdown_button2: ^1.1.1
  app_settings: ^4.1.1
  get_storage:
  in_app_review: ^2.0.4
  device_info_plus: ^3.2.2
  ios_utsname_ext: ^2.1.0
  package_info_plus: ^1.3.1
  connectivity_plus: ^2.2.1
  photo_manager: ^2.1.2
  fl_chart: ^0.51.0
  expandable_page_view: ^1.0.13
  link_preview_generator: ^1.2.0
  image_crop: ^0.4.0
  photo_view: ^0.14.0
  web_socket_channel: ^2.2.0
  sqflite: ^2.0.2+1
  sqlite_viewer: ^1.0.5
  path: ^1.8.0
  internet_connection_checker: ^0.0.1+3
  clickable_list_wheel_view: ^0.1.0
  scrollable_positioned_list: ^0.2.3
  flutter_list_view: ^1.1.18
  scrolls_to_top: ^1.1.1
  receive_sharing_intent: ^1.4.2
  time_machine: ^0.9.11
  flutter_slidable: ^1.3.0
  cp949_dart: ^1.0.0+1
  flutter_local_notifications: ^9.9.0
  zoom_pinch_overlay: ^1.2.0
  palette_generator: ^0.3.3
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

  flutter_native_splash: ^2.1.6

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/illustrations/logo_icon.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/illustrations/
    - assets/lotties/
    - images/pic1.png

  fonts:
    - family: Nanum
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
        - asset: assets/fonts/NanumSquareRoundR.ttf
        - asset: assets/fonts/NanumSquareRoundB.ttf
        - asset: assets/fonts/NanumSquareRoundEB.ttf
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUIT-Heavy.ttf
          weight: 900
        - asset: assets/fonts/SUIT-Light.ttf
          weight: 300
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Thin.ttf
          weight: 100
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf  
