name: loopus
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4
  cached_network_image: ^3.1.0
  favorite_button: ^0.0.4
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  image_picker: ^0.8.4+4
  smooth_page_indicator: ^1.0.0+2
  http: ^0.13.4
  image_cropper: ^1.4.1
  device_preview: ^1.0.0
  pull_to_refresh: ^2.0.0
  sticky_headers: ^0.2.0
  underline_indicator: ^0.0.4
  webview_flutter: ^3.0.0
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  intl: ^0.17.0
  lottie: ^1.2.1
  flutter_datetime_picker: ^1.5.1
  # kakao_flutter_sdk: ^0.9.0
  flutter_keyboard_visibility: ^5.1.1
  dropdown_button2: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/illustrations/
    - assets/lotties/

  fonts:
    - family: Nanum
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
        - asset: assets/fonts/NanumSquareRoundR.ttf
        - asset: assets/fonts/NanumSquareRoundB.ttf
        - asset: assets/fonts/NanumSquareRoundEB.ttf
