// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-TEarVtqL2f1uuVG2IEZkF1ZGq-uHv24',
    appId: '1:840100932483:web:322e379a5e256ca6a0a4b6',
    messagingSenderId: '840100932483',
    projectId: 'loopus-bb12f',
    authDomain: 'loopus-bb12f.firebaseapp.com',
    storageBucket: 'loopus-bb12f.appspot.com',
    measurementId: 'G-MTS70V0VTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8IN4PV6DCK3zQ2Kxl-D0qS8K3rxRuOBc',
    appId: '1:840100932483:android:0fc60b47f27be6e8a0a4b6',
    messagingSenderId: '840100932483',
    projectId: 'loopus-bb12f',
    storageBucket: 'loopus-bb12f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyY0H6mpqq3yLUWD7hJ-EsSfUN7pbv3g',
    appId: '1:840100932483:ios:1c246b507c36264ba0a4b6',
    messagingSenderId: '840100932483',
    projectId: 'loopus-bb12f',
    storageBucket: 'loopus-bb12f.appspot.com',
    iosClientId: '840100932483-gfu3gepjb9fusvls2ce3r7kr0p6jujcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loopusfrontendDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnyY0H6mpqq3yLUWD7hJ-EsSfUN7pbv3g',
    appId: '1:840100932483:ios:1c246b507c36264ba0a4b6',
    messagingSenderId: '840100932483',
    projectId: 'loopus-bb12f',
    storageBucket: 'loopus-bb12f.appspot.com',
    iosClientId: '840100932483-gfu3gepjb9fusvls2ce3r7kr0p6jujcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loopusfrontendDesign',
  );
}
